#ifndef PROTOCOL_H
#define PROTOCOL_H

typedef unsigned int uint;

enum ENUM_TYPE{
    ENUM_TYPE_MIN=0,
    ENUM_TYPE_REGIST_REQUEST,
    ENUM_TYPE_REGIST_RESPOND,
    ENUM_TYPE_LOGIN_REQUEST,
    ENUM_TYPE_LOGIN_RESPOND,
    ENUM_TYPE_FIND_USER_REQUEST,
    ENUM_TYPE_FIND_USER_RESPOND,
    ENUM_TYPE_ONLINEUSER_REQUEST,
    ENUM_TYPE_ONLINEUSER_RESPOND,
    ENUM_TYPE_ADD_FRIEND_REQUEST,
    ENUM_TYPE_ADD_FRIEND_RESPOND,
    ENUM_TYPE_ADD_FRIEND_RESEND,
    ENUM_TYPE_ADD_FRIEND_AGREE_REQUEST,
    ENUM_TYPE_ADD_FRIEND_AGREE_RESPOND,
    ENUM_TYPE_FLUSH_FRIEND_REQUEST,
    ENUM_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_TYPE_DEL_FRIEND_REQUEST,
    ENUM_TYPE_DEL_FRIEND_RESPOND,
    ENUM_TYPE_CHAT_REQUEST,
    ENUM_TYPE_CHAT_RESPOND,
    ENUM_TYPE_CHAT_RESEND,
    ENUM_TYPE_MKDIR_REQUEST,
    ENUM_TYPE_MKDIR_RESPOND,
    ENUM_TYPE_FLUSH_FILE_REQUEST,
    ENUM_TYPE_FLUSH_FILE_RESPOND,
    ENUM_TYPE_DEL_DIR_REQUEST,
    ENUM_TYPE_DEL_DIR_RESPOND,
    ENUM_TYPE_RENAME_FILE_REQUEST,
    ENUM_TYPE_RENAME_FILE_RESPOND,
    ENUM_TYPE_MOVE_FILE_REQUEST,
    ENUM_TYPE_MOVE_FILE_RESPOND,
    ENUM_TYPE_UPLOAD_FILE_REQUEST,
    ENUM_TYPE_UPLOAD_FILE_RESPOND,
    ENUM_TYPE_DOWNLOAD_FILE_REQUEST,
    ENUM_TYPE_DOWNLOAD_FILE_RESPOND,
    ENUM_TYPE_SHARE_FILE_REQUEST,
    ENUM_TYPE_SHARE_FILE_RESPOND,
    ENUM_TYPE_MAX=99999,
};

struct PDU{
    uint uiTotalLen;
    uint uiMsgLen;
    uint uiType;
    char caData[64];
    char caMsg[];
};

PDU *mkPDU(uint uiMsgLen=0);



#endif // PROTOCOL_H
